apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "{{DEPLOYMENT_NAME}}"
  namespace: "default"
  labels:
    team: "teamsykefravr"
spec:
  image: "repo.adeo.no:5443/syfo/syfosmmqmock:@@VERSION@@"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
    - name: MQ_HOST
      value: {{MQ_HOST}}
    - name: MQ_PORT
      value: '{{MQ_PORT}}'
    - name: MQ_QUEUE_MANAGER
      value: {{MQ_QUEUE_MANAGER}}
    - name: MQ_CHANNEL
      value: {{MQ_CHANNEL}}
    - name: MQ_INPUT_QUEUE
      value: {{MQ_INPUT_QUEUE}}
    - name: SMID_XPATH
      value: {{SMID_XPATH}}
    - name: SM_STEP
      value: {{SM_STEP}}
